module.exports = {
    beforeEach: browser => browser.url('https://alpha.yoodlize.com/'),
    after: browser => browser.end(),
    'See all': browser => {
        browser
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[1]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Tools')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[2]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Outdoor Gear')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[3]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Electronics')
            .back()
            .pause(2000)
            .useXpath()

            .click("(//*[contains(@class,'fmVgeN')])[4]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Party & Wedding Equipment')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[5]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Recreational Vehicles')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[6]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", ' Clothing')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[7]")
            .useCss()
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Home and Kitchen')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[8]")
            .useCss()
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Toys and Games')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[9]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Lawn and Garden')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[10]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Sporting Good')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[11]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'DVDs & Video Games')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[12]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Venues')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[13]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Local Experts')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[14]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Experiences')
            .back()
            .pause(2000)
            .useXpath()
            .click("(//*[contains(@class,'fmVgeN')])[15]")
            .useCss()
            .pause(500)
            .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Misc')
            .back()
         },

         'Browse Categories': browser =>{
             browser
             .useXpath()
             .click('//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Tools')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[2]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Outdoor Gear')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[3]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Electronics')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[4]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Party')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[5]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Recreational')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[6]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Clothing')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[7]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Home')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[8]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Toys')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[9]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Lawn')
             .back().useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[10]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Sporting')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[11]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'DVDs & Video Games')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[12]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Venues')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[13]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Local')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[14]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Experiences')
             .back()
             .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[15]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Music')
            .back()
            .useXpath()
             .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[16]')
             .pause(3000)
             .useCss()
             .pause(500)
             .assert.containsText("[class='sc-jKVCRD jSqgxr']", 'Misc')
             .back()

             




         }











}






